Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'

  root to: "page#index"
  get "/projects", to: "page#project"
  get "/about", to: "page#about"
  get "/contact", to: "page#contact"
  post "/contact", to: "page#submitcontact"

  get "/tools", to: "tool#index"
  get "/tools/settings", to: "tool#settings"
  post "/tools/settings/session/debug", to: "tool#settings"
  post "/tools/settings/session/dyslexic", to: "tool#settings"
  post "/tools/settings/session/style", to: "tool#settings"
  get "/tools/wordrand", to: "tool#wordrand"
  get "/tools/yourand", to: "tool#yourand"
  get "/tools/wordgen", to: "tool#wordgen"
  get "/tools/redrand", to: "tool#redrand"
  get "/tools/alpaca", to: "tool#alpaca"
  get "/tools/cells", to: "tool#cells"
  get "/tools/dither", to: "tool#dither"
  get "/tools/lavalamp", to: "tool#lavalamp"
  get "/tools/soundvisualiser", to: "tool#soundvisualiser"
  get "/tools/replayer", to: "tool#replayer"
  get "/tools/vic", to: "tool#vic"
  get "/tools/bean", to: "tool#bean"
  get "/tools/uwu", to: "tool#uwu"
  get "/tools/crytyper", to: "tool#crytyper"
  get "/tools/sarcasm", to: "tool#sarcasm"
  get "/tools/css-streamliner", to: "tool#cssStreamliner"
  get "/tools/divvy", to: "tool#divCounter"
  post "/tools/divvy", to: "tool#divCounter"
  resources :messages, only: [:new, :create]
  get "/tools/chat", to: "tool#chatindex"
  post "/tools/chat/nickname", to: "tool#chatsetnickname"
  post "/tools/chat/new", to: "tool#chatnew"
  get "/tools/chat/:roomno", to: "tool#chat"

  get "/blog", to: "blog#index"
  get "/blog/edit", to: "blog#edit"
  post "/blog/edit", to: "blog#submitedit"
  get "/blog/delete", to: "blog#delete"
  get "/blog/add", to: "blog#add"
  post "/blog/add", to: "blog#submitadd"
  get "/blog/:id", to: "blog#show"
  get "/blogs/:id/:name", to: "blog#aprilfools"
  get "/blog/:id/:name", to: "blog#show"
  
  get "/login", to: "login#login"
  get '/callback', to: "login#callback"
  get "/logout", to: "login#logout"

  get "/admin*", to: "admin#index"
  post "/admin*", to: "admin#index"
  get "/admin", to: "admin#index"
  get "/admin/cv", to: "admin#cv"
  get "/admin/database", to: "admin#database"
  post "/admin/database", to: "admin#database"
  get "/admin/todo", to: "admin#todo"
  post "/admin/todo", to: "admin#todo"
  get "/admin/todo/:id", to: "admin#todo"
  post "/admin/todo/:id", to: "admin#todo"
end
